### ISSUE TITLE
fix: generate module with a path

### ISSUE THREAD

**Issue by DopeMeerkat** [vuesion/docs#9]
when running `npm run generate` to generate module using a path (i.e. Pages/test), `router.ts` and `state.ts` doesn't use correct path

Expected path: './Pages/test/state'
Generated path: './test/state'

**Comment by devCrossNet** [comment]
That issue is fixed in the latest release (`@vuesion/service: v3.1.1`):

```
vuesion generate

? [PLOP] Please choose a generator. Empty Module - Add a module with VueX store and routes
? What should it be called? pages/test
? Do you want routes? Yes
? Do you want vuex? Yes
```

results in router.ts:

```
import { TestRoutes } from './pages/test/routes';
```

state.ts:
```
import { ITestState } from './pages/test/state';
```

**Comment by devCrossNet** [comment]
@DopeMeerkat can this be closed?

**Comment by devCrossNet** [comment]
no response - closed.
